import type { Metadata } from 'next';
import './globals.css';
import { Navbar } from '@/src/components/homepage/navbar';
import { Footer } from '@/src/components/footer';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className=" pt-[clamp(0.5rem,2vw,1.7rem)] flex flex-col px-[clamp(0.5rem,6vw,5rem)]">
          <Navbar>
            {children}
            <Footer />
          </Navbar>
        </div>
      </body>
    </html>
  );
}
